# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wynk Health
email: info@wynkhealth.com
description: >-
  At Wynk Health, we're dedicated to helping patients interact with their healthcare providers more effectively. 
  Our innovative solutions are coming in 2025.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wynkhealth.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wynkhealth
github_username: wynkhealth

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - assets/css/main.css # Exclude the source CSS file but not the generated one

# Include these files/folders that Jekyll would otherwise exclude by default
include:
  - CNAME
  - assets/css/style.css # Explicitly include the generated CSS file

# Default front matter for pages
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "home"
